// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/// @title GovernanceDAO
/// @notice Token-weighted DAO with proposal + voting generated by Axtion
contract GovernanceDAO is ReentrancyGuard {
    IERC20 public immutable governanceToken;
    uint256 public votingPeriod;
    uint256 public quorumVotes;
    uint256 public proposalCount;

    enum ProposalState { Active, Passed, Rejected, Executed }

    struct Proposal {
        uint256 id;
        address proposer;
        string description;
        uint256 forVotes;
        uint256 againstVotes;
        uint256 deadline;
        ProposalState state;
        bytes callData;
        address target;
    }

    mapping(uint256 => Proposal) public proposals;
    mapping(uint256 => mapping(address => bool)) public hasVoted;

    event ProposalCreated(uint256 indexed id, address proposer, string description);
    event Voted(uint256 indexed proposalId, address voter, bool support, uint256 votes);
    event ProposalExecuted(uint256 indexed id);

    constructor(address governanceToken_, uint256 votingPeriod_, uint256 quorumVotes_) {
        governanceToken = IERC20(governanceToken_);
        votingPeriod = votingPeriod_;
        quorumVotes = quorumVotes_;
    }

    function propose(string calldata description, address target, bytes calldata data) external returns (uint256) {
        require(governanceToken.balanceOf(msg.sender) > 0, "Must hold tokens to propose");
        uint256 id = ++proposalCount;
        proposals[id] = Proposal({
            id: id, proposer: msg.sender, description: description,
            forVotes: 0, againstVotes: 0, deadline: block.timestamp + votingPeriod,
            state: ProposalState.Active, callData: data, target: target
        });
        emit ProposalCreated(id, msg.sender, description);
        return id;
    }

    function vote(uint256 proposalId, bool support) external {
        Proposal storage p = proposals[proposalId];
        require(p.state == ProposalState.Active, "Not active");
        require(block.timestamp <= p.deadline, "Voting ended");
        require(!hasVoted[proposalId][msg.sender], "Already voted");
        uint256 votes = governanceToken.balanceOf(msg.sender);
        require(votes > 0, "No voting power");
        hasVoted[proposalId][msg.sender] = true;
        if (support) p.forVotes += votes;
        else p.againstVotes += votes;
        emit Voted(proposalId, msg.sender, support, votes);
    }

    function execute(uint256 proposalId) external nonReentrant {
        Proposal storage p = proposals[proposalId];
        require(block.timestamp > p.deadline, "Voting not ended");
        require(p.state == ProposalState.Active, "Already finalized");
        if (p.forVotes >= quorumVotes && p.forVotes > p.againstVotes) {
            p.state = ProposalState.Passed;
            (bool ok,) = p.target.call(p.callData);
            require(ok, "Execution failed");
            p.state = ProposalState.Executed;
            emit ProposalExecuted(proposalId);
        } else {
            p.state = ProposalState.Rejected;
        }
    }
}
